tabela = ('Palmeiras', 'Internacional', 'Fluminense', 'Corinthians', 'Flamengo', 'Athletico-PR', 'Atlético-MG', 'Fortaleza', 'São Paulo', 'América-MG', 'Botafogo', 'Santos', 'Goiás', 'Bragantino', 'Coritiba', 'Cuiabá', 'Ceará SC', 'Atlético-GO', 'Avaí', 'Juventide')
print('-=-'*10)
count = tabela.count('Chapecoense')
print(f'Os cinco primeiros colocados do brasileirão 2022 foram: {tabela[:5]}')
print('-=-'*10)
print(f'Os últimos quatro times na tabela do brasileirão são: {tabela[16:]}')
print('-=-'*10)
print(f'Os times em ordem alfabética do brasileirão 2022 são: {sorted(tabela)}')
print('-=-'*10)
print(f'A posição da chapecoense na tabela é: {count}')
print('-=-'*10)
